In [1]:
import pandas as pd

In [22]:
data = pd.read_csv('clean_data_heart.csv')

In [23]:
data.shape

(918, 12)

In [24]:
data

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,1,2,140,289,0,0,172,0,0.0,1,0
1,49,0,3,160,180,0,0,156,0,1.0,2,1
2,37,1,2,130,283,0,1,98,0,0.0,1,0
3,48,0,4,138,214,0,0,108,1,1.5,2,1
4,54,1,3,150,195,0,0,122,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,1,110,264,0,0,132,0,1.2,2,1
914,68,1,4,144,193,1,0,141,0,3.0,2,1
915,57,1,4,130,131,0,0,115,1,1.2,2,1
916,57,0,2,130,236,0,2,174,0,0.0,2,1
917,38,1,3,138,175,0,0,173,0,0.0,1,0

In [25]:
def encode_sex(sex):
    sex = sex
    if sex == 0:
        sex = 'perempuan'
    else:
        sex = 'laki-laki'
        
    return sex

def encode_cpt(cpt):
    cpt = cpt
    if cpt == 1:
        cpt = 'typical angina'
    elif cpt == 2:
        cpt = 'atypical angina'
    elif cpt == 3:
        cpt = 'non-anginal pain'
    else:
        cpt = 'asymptomatic'
        
    return cpt

def encode_fbs(fbs):
    fbs = fbs
    if fbs == 0:
        fbs = '<120'
    else:
        fbs = '>120'
        
    return fbs

def encode_re(re):
    re = re
    if re == 0:
        re = 'Normal'
    elif re == 1:
        re = 'ST-T Abnormal'
    else:
        re = 'Hipertrophy'
        
    return re

def encode_ea(ea):
    ea = ea
    if ea == 0:
        ea = 'tidak'
    else:
        ea = 'ya'
        
    return ea

def encode_ss(ss):
    ss = ss
    if ss == 1:
        ss = 'upsloping'
    elif ss == 2:
        ss = 'flat'
    else:
        ss = 'downsloping'
        
    return ss

def encode_tr(tr):
    tr = tr
    if tr == 0:
        tr = 'tidak terkena penyakit'
    else:
        tr = 'terkena penyakit'
        
    return tr

In [26]:
gender = {'1.Laki-laki': 1, '0.Perempuan': 0}
chest_pain_type = {'1. typical angina': 1,
                   '2. atypical angina': 2,
                   '3. non-anginal pain': 3,
                   '4. asymptomatic ': 4}
fasting_blood_sugar = {'1. > 120': 1, '0. <120': 0}
resting_ecg = {'0. Normal': 0, '1. ST-T Abnormal': 1, '2. Hipertrophy ': 2}
exercise_angina = {'1. Ya': 1, '0.Tidak': 0}
ST_slope = {'1.upsloping': 1, '2.flat': 2, '3.downsloping': 3}

In [27]:
data['sex'] = data['sex'].apply(lambda x : encode_sex(x) )
data['chest pain type'] = data['chest pain type'].apply(lambda x : encode_cpt(x) )
data['fasting blood sugar'] = data['fasting blood sugar'].apply(lambda x : encode_fbs(x) )
data['resting ecg'] = data['resting ecg'].apply(lambda x : encode_re(x) )
data['exercise angina'] = data['exercise angina'].apply(lambda x : encode_ea(x) )
data['ST slope'] = data['ST slope'].apply(lambda x : encode_ss(x) )
data['target'] = data['target'].apply(lambda x : encode_tr(x) )

In [28]:
data

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,laki-laki,atypical angina,140,289,<120,Normal,172,tidak,0.0,upsloping,tidak terkena penyakit
1,49,perempuan,non-anginal pain,160,180,<120,Normal,156,tidak,1.0,flat,terkena penyakit
2,37,laki-laki,atypical angina,130,283,<120,ST-T Abnormal,98,tidak,0.0,upsloping,tidak terkena penyakit
3,48,perempuan,asymptomatic,138,214,<120,Normal,108,ya,1.5,flat,terkena penyakit
4,54,laki-laki,non-anginal pain,150,195,<120,Normal,122,tidak,0.0,upsloping,tidak terkena penyakit
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,laki-laki,typical angina,110,264,<120,Normal,132,tidak,1.2,flat,terkena penyakit
914,68,laki-laki,asymptomatic,144,193,>120,Normal,141,tidak,3.0,flat,terkena penyakit
915,57,laki-laki,asymptomatic,130,131,<120,Normal,115,ya,1.2,flat,terkena penyakit
916,57,perempuan,atypical angina,130,236,<120,Hipertrophy,174,tidak,0.0,flat,terkena penyakit
917,38,laki-laki,non-anginal pain,138,175,<120,Normal,173,tidak,0.0,upsloping,tidak terkena penyakit

In [29]:
data.to_csv('data_encode.csv', index=False)

In [30]:
data['ST slope'].value_counts()

flat           459
upsloping      395
downsloping     64
Name: ST slope, dtype: int64